server:
  port: 8084
  tomcat:
    threads:
      max: 14
  jetty:
    threads:
      max: 14
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework.security: DEBUG
    io.jsonwebtoken: DEBUG
spring:
#  datasource:
#    url: jdbc:mysql://91.234.194.31:3306/c0cagnotte
#    username: c0cagnotte
#    password: cagnotte123
  datasource:
    url: jdbc:mysql://localhost:3306/projet_cagnotte
    username: root
    password:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
  profiles:
    active: debug
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: kfnazezfdajiefjpoehiuhiuhhkjfdslgpreuiehfshrs
  application:
    name: Cagnotte