server:
  port: ${SERVER_PORT:8080}
  tomcat:
    threads:
      max: 14
  jetty:
    threads:
      max: 14
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework.security: DEBUG
    io.jsonwebtoken: DEBUG
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
  profiles:
    active: debug
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: kfnazezfdajiefjpoehiuhiuhhkjfdslgpreuiehfshrs
  application:
    name: CagnotteApplication
    accessTokenValidityMinutes: 1440