server:
  port: 81
  tomcat:
    threads:
      max: 14
  jetty:
    threads:
      max: 14
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    url: jdbc:mysql://91.234.194.31:3306/c0cagnotte
    username: c0cagnotte
    password: cagnotte123
#  datasource:
#    url: jdbc:mysql://localhost:3306/projet_cagnotte
#    username: root
#    password:
  profiles:
    active: debug
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: Cagnotte